-- seeds_quad_periods.sql
-- 2026-09-24 -- intentionally holds NO data. This file used to seed
-- ref_quad_periods.monthly rows (quad1_pct..quad4_pct) with a one-time
-- 2026-06-21 chart capture, re-applied via `ON CONFLICT ... DO UPDATE` on
-- every `python -m db.init_db` run -- which meant any manual correction
-- made in the /ref UI got silently reverted back to that stale capture the
-- next time init_db ran (caught 2026-09-24: user's corrected September
-- distribution kept reverting to old numbers; root-caused to this file).
--
-- The monthly quad distribution changes weekly (new Hedgeye forecast chart
-- each week) and is maintained by hand in /ref -- it does not belong in a
-- seed file at all. `db/init_db.py::DDL_FILES` globs every db/*.sql file,
-- so this file still runs on every init_db -- it is kept as a placeholder,
-- with this comment as the record of why, rather than deleted outright.
-- Do not add INSERT/ON CONFLICT DO UPDATE statements for ref_quad_periods
-- here again.
