-- Auto-generated from ref_ma_columns registry
-- DO NOT EDIT BY HAND

-- drv_cat_action_decision
DROP TABLE IF EXISTS drv_cat_action_decision CASCADE;
CREATE TABLE drv_cat_action_decision (
  as_of_date         DATE NOT NULL,
  symbol             TEXT NOT NULL,
  "3mn_stk_outlook_sd"                     NUMERIC,
  "3w_stk_outlook_sd"                      NUMERIC,
  overall_group                            TEXT,
  action_type                              TEXT,
  l1                                       TEXT,
  l2                                       TEXT,
  neg_outlook                              TEXT,
  pos_outlook                              TEXT,
  oa_group                                 TEXT,
  l3                                       TEXT,
  opposite_outlook                         TEXT,
  outlook                                  TEXT,
  final_action                             TEXT,
  entry                                    TEXT,
  cont                                     TEXT,
  overall                                  TEXT,
  source_run_id      BIGINT,
  computed_at        TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (as_of_date, symbol)
);

-- drv_cat_atomic_input
DROP TABLE IF EXISTS drv_cat_atomic_input CASCADE;
CREATE TABLE drv_cat_atomic_input (
  as_of_date         DATE NOT NULL,
  symbol             TEXT NOT NULL,
  macdh_direction                          NUMERIC,
  macd_direction                           NUMERIC,
  bb_direction                             NUMERIC,
  bb_threshold                             NUMERIC,
  bbthresh_co_days                         NUMERIC,
  bbthresh_co_days2                        NUMERIC,
  trade_cross_over                         NUMERIC,
  trade_rule                               NUMERIC,
  not_trade_rule                           NUMERIC,
  "!trade_rule"                            NUMERIC,
  trend_cross_over                         NUMERIC,
  trend_rule                               NUMERIC,
  "!trend_rule"                            NUMERIC,
  not_trend_rule                           NUMERIC,
  trend_trade_dep_rule                     NUMERIC,
  trtn_relation                            NUMERIC,
  "!trtn_relation"                         NUMERIC,
  not_trtn_relation                        NUMERIC,
  trade_trend_sd_rule                      NUMERIC,
  brrpct_rule                              NUMERIC,
  brrpct_lrr                               NUMERIC,
  brrpct_r2                                NUMERIC,
  brrpct_lrr2                              NUMERIC,
  brrpct_trr                               NUMERIC,
  brrpct_puts                              NUMERIC,
  brrpct_trr_puts                          NUMERIC,
  brrpct_dir                               NUMERIC,
  high_trr                                 NUMERIC,
  low_lrr                                  NUMERIC,
  trend_below_trr                          NUMERIC,
  lrr_above_trade                          NUMERIC,
  trr_idx                                  NUMERIC,
  mrr_idx                                  NUMERIC,
  lrr_idx                                  NUMERIC,
  hvabsolute                               NUMERIC,
  ivabsolute                               NUMERIC,
  ivpercentile                             NUMERIC,
  ivpercentile_puts                        NUMERIC,
  hvpercentile                             NUMERIC,
  hvpercentile_puts                        NUMERIC,
  ivhv                                     NUMERIC,
  ivhv_puts                                NUMERIC,
  ivrule                                   NUMERIC,
  rsi_rule                                 NUMERIC,
  rsi_top                                  NUMERIC,
  rsi_puts                                 NUMERIC,
  c_3m_low_rule                            NUMERIC,
  "3m_low_rule"                            NUMERIC,
  "3m_low_days_rule"                       NUMERIC,
  c_3m_low_days_rule                       NUMERIC,
  c_3mn_high_rule                          NUMERIC,
  "3mn_high_rule"                          NUMERIC,
  c_3mn_high_days_rule                     NUMERIC,
  "3mn_high_days_rule"                     NUMERIC,
  c_3m_long                                NUMERIC,
  "3m_long"                                NUMERIC,
  perf3mn_sd_rule                          NUMERIC,
  perf2m_sd_rule                           NUMERIC,
  perf3wk_sd_rule                          NUMERIC,
  perf2wk_sd_rule                          NUMERIC,
  perf3d_sd_rule                           NUMERIC,
  perf1d_sd_rule                           NUMERIC,
  not_perf1d_sd                            NUMERIC,
  "!perf1d_sd"                             NUMERIC,
  perf3d_sd_1off                           NUMERIC,
  perf_sd_rule                             NUMERIC,
  "!perf_sd_rule"                          NUMERIC,
  not_perf_sd_rule                         NUMERIC,
  "!perf3d_rule"                           NUMERIC,
  not_perf3d_rule                          NUMERIC,
  bbhighlow_sd_rule                        NUMERIC,
  bbhighlow_days_rule                      NUMERIC,
  bbstreak_rule                            NUMERIC,
  bbstreakrule1                            NUMERIC,
  bbstreak_rule2                           NUMERIC,
  bbstreak_days_rule                       NUMERIC,
  bbstreak_days_rule2                      NUMERIC,
  bbstreak_days_rule3                      NUMERIC,
  bbstreak_days_rule4                      NUMERIC,
  bb_bull_rule                             NUMERIC,
  bb_bull_puts                             NUMERIC,
  bbhighdays                               NUMERIC,
  bblowdays                                NUMERIC,
  macd_rule                                NUMERIC,
  macdh_rule                               NUMERIC,
  macd_and_h_rule                          NUMERIC,
  macd_brr_puts                            NUMERIC,
  macdh_brr_puts                           NUMERIC,
  macd_and_h_rule_puts                     NUMERIC,
  macdh_days                               NUMERIC,
  macdh_days2                              NUMERIC,
  overbought                               NUMERIC,
  "!overbought"                            NUMERIC,
  not_overbought                           NUMERIC,
  c_3mn_outlook                            NUMERIC,
  "3mn_outlook"                            NUMERIC,
  "3mn_outlook_days"                       NUMERIC,
  c_3mn_outlook_days                       NUMERIC,
  "3wk_outlook"                            NUMERIC,
  c_3wk_outlook                            NUMERIC,
  c_3wk_outlook_days                       NUMERIC,
  "3wk_outlook_days"                       NUMERIC,
  "!3wk_ol"                                NUMERIC,
  not_3wk_ol                               NUMERIC,
  "!3wk_ol_days"                           NUMERIC,
  not_3wk_ol_days                          NUMERIC,
  bull                                     NUMERIC,
  not_bull                                 NUMERIC,
  "!bull"                                  NUMERIC,
  perforbull                               NUMERIC,
  not_perforbull                           NUMERIC,
  "!perforbull"                            NUMERIC,
  "50_dma_rule"                            NUMERIC,
  c_50_dma_rule                            NUMERIC,
  "50_dma_crossover"                       NUMERIC,
  c_50_dma_crossover                       NUMERIC,
  c_200_dma_rule                           NUMERIC,
  "200_dma_rule"                           NUMERIC,
  c_200_dma_crossover                      NUMERIC,
  "200_dma_crossover"                      NUMERIC,
  c_52_wk_low_rule                         NUMERIC,
  "52_wk_low_rule"                         NUMERIC,
  "52_wk_high_rule"                        NUMERIC,
  c_52_wk_high_rule                        NUMERIC,
  brrtrade                                 NUMERIC,
  trrtrade                                 NUMERIC,
  up_resistance                            NUMERIC,
  down_resistance                          NUMERIC,
  earnings                                 NUMERIC,
  vs_price                                 NUMERIC,
  vs_volume_spike                          NUMERIC,
  vs_volatility                            NUMERIC,
  vs_days                                  NUMERIC,
  vs_lt_outlook_rule                       NUMERIC,
  current_price_sd_rule                    NUMERIC,
  current_volume_rule                      NUMERIC,
  current_volatility_rule                  NUMERIC,
  short_term_oulook_if_lt_bullish          NUMERIC,
  short_term_oulook_if_lt_bearish          NUMERIC,
  source_run_id      BIGINT,
  computed_at        TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (as_of_date, symbol)
);

-- drv_cat_bollinger
DROP TABLE IF EXISTS drv_cat_bollinger CASCADE;
CREATE TABLE drv_cat_bollinger (
  as_of_date         DATE NOT NULL,
  symbol             TEXT NOT NULL,
  a_bbhighlow                              NUMERIC,
  bbhighlow_a                              NUMERIC,
  bbhighlow                                NUMERIC,
  bbhighlowdays                            NUMERIC,
  bb_direction1                            NUMERIC,
  bbhighlow_sd                             NUMERIC,
  a_bbhighlowdays                          NUMERIC,
  a_bb_streak                              NUMERIC,
  bb_streak_1                              NUMERIC,
  bb_streak_2                              NUMERIC,
  bb_streak_cur                            NUMERIC,
  bb_threshold_crossover                   NUMERIC,
  bb_streak                                NUMERIC,
  bb_streak_days                           NUMERIC,
  bb_bot_prev                              NUMERIC,
  bb_top_prev                              NUMERIC,
  bb_brrpct                                NUMERIC,
  bb_bot_15d                               NUMERIC,
  bb_bot_7d                                NUMERIC,
  bb_bot_3d                                NUMERIC,
  bb_bot_slope                             NUMERIC,
  bb_top_15d                               NUMERIC,
  bb_top_7d                                NUMERIC,
  bb_top_3d                                NUMERIC,
  bb_tot_slope                             NUMERIC,
  bb_slope                                 NUMERIC,
  bb_bull                                  NUMERIC,
  a_bb_bot_slope                           NUMERIC,
  a_bb_top_slope                           NUMERIC,
  td_tn_bb_risk_range_rule_action_seq      NUMERIC,
  td_tn_bb_risk_range_rule_action          NUMERIC,
  source_run_id      BIGINT,
  computed_at        TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (as_of_date, symbol)
);

-- drv_cat_composite
DROP TABLE IF EXISTS drv_cat_composite CASCADE;
CREATE TABLE drv_cat_composite (
  as_of_date         DATE NOT NULL,
  symbol             TEXT NOT NULL,
  "=trig!o1"                               NUMERIC,
  "=trig_not_o1"                           NUMERIC,
  "=trig_not_q1"                           NUMERIC,
  "=trig!q1"                               NUMERIC,
  "=trig!s1"                               NUMERIC,
  "=trig_not_s1"                           NUMERIC,
  "=trig_not_u1"                           NUMERIC,
  "=trig!u1"                               NUMERIC,
  "=trig!w1"                               NUMERIC,
  "=trig_not_w1"                           NUMERIC,
  "=trig_not_y1"                           NUMERIC,
  "=trig!y1"                               NUMERIC,
  "=trig_not_aa1"                          NUMERIC,
  "=trig!aa1"                              NUMERIC,
  "=trig_not_ac1"                          NUMERIC,
  "=trig!ac1"                              NUMERIC,
  "=trig!ae1"                              NUMERIC,
  "=trig_not_ae1"                          NUMERIC,
  "=trig_not_ag1"                          NUMERIC,
  "=trig!ag1"                              NUMERIC,
  "=trig!ai1"                              NUMERIC,
  "=trig_not_ai1"                          NUMERIC,
  "=trig_not_ak1"                          NUMERIC,
  "=trig!ak1"                              NUMERIC,
  "=trig_not_am1"                          NUMERIC,
  "=trig!am1"                              NUMERIC,
  "=trig!ao1"                              NUMERIC,
  "=trig_not_ao1"                          NUMERIC,
  "=trig!aq1"                              NUMERIC,
  "=trig_not_aq1"                          NUMERIC,
  "=trig!as1"                              NUMERIC,
  "=trig_not_as1"                          NUMERIC,
  "=trig!au1"                              NUMERIC,
  "=trig_not_au1"                          NUMERIC,
  "=trig!aw1"                              NUMERIC,
  "=trig_not_aw1"                          NUMERIC,
  "=trig!ay1"                              NUMERIC,
  "=trig_not_ay1"                          NUMERIC,
  "=trig_not_ba1"                          NUMERIC,
  "=trig!ba1"                              NUMERIC,
  "=trig_not_bc1"                          NUMERIC,
  "=trig!bc1"                              NUMERIC,
  "=trig!be1"                              NUMERIC,
  "=trig_not_be1"                          NUMERIC,
  "=trig!bg1"                              NUMERIC,
  "=trig_not_bg1"                          NUMERIC,
  "=trig!bi1"                              NUMERIC,
  "=trig_not_bi1"                          NUMERIC,
  "=trig_not_bk1"                          NUMERIC,
  "=trig!bk1"                              NUMERIC,
  "=trig!bm1"                              NUMERIC,
  "=trig_not_bm1"                          NUMERIC,
  "=trig!bo1"                              NUMERIC,
  "=trig_not_bo1"                          NUMERIC,
  "=trig_not_bq1"                          NUMERIC,
  "=trig!bq1"                              NUMERIC,
  "=trig!bs1"                              NUMERIC,
  "=trig_not_bs1"                          NUMERIC,
  "=trig_not_bu1"                          NUMERIC,
  "=trig!bu1"                              NUMERIC,
  "=trig!bw1"                              NUMERIC,
  "=trig_not_bw1"                          NUMERIC,
  "=trig!by1"                              NUMERIC,
  "=trig_not_by1"                          NUMERIC,
  "=trig!ca1"                              NUMERIC,
  "=trig_not_ca1"                          NUMERIC,
  "=trig!cc1"                              NUMERIC,
  "=trig_not_cc1"                          NUMERIC,
  "=trig!ce1"                              NUMERIC,
  "=trig_not_ce1"                          NUMERIC,
  "=trig_not_cg1"                          NUMERIC,
  "=trig!cg1"                              NUMERIC,
  "=trig!ci1"                              NUMERIC,
  "=trig_not_ci1"                          NUMERIC,
  "=trig!ck1"                              NUMERIC,
  "=trig_not_ck1"                          NUMERIC,
  "=trig_not_cm1"                          NUMERIC,
  "=trig!cm1"                              NUMERIC,
  "=trig_not_co1"                          NUMERIC,
  "=trig!co1"                              NUMERIC,
  "=trig!cq1"                              NUMERIC,
  "=trig_not_cq1"                          NUMERIC,
  "=trig_not_cs1"                          NUMERIC,
  "=trig!cs1"                              NUMERIC,
  "=trig!cu1"                              NUMERIC,
  "=trig_not_cu1"                          NUMERIC,
  "=trig_not_cw1"                          NUMERIC,
  "=trig!cw1"                              NUMERIC,
  "=trig_not_cy1"                          NUMERIC,
  "=trig!cy1"                              NUMERIC,
  "=trig_not_da1"                          NUMERIC,
  "=trig!da1"                              NUMERIC,
  "=trig_not_dc1"                          NUMERIC,
  "=trig!dc1"                              NUMERIC,
  "=trig_not_de1"                          NUMERIC,
  "=trig!de1"                              NUMERIC,
  "=trig_not_dg1"                          NUMERIC,
  "=trig!dg1"                              NUMERIC,
  "=trig!di1"                              NUMERIC,
  "=trig_not_di1"                          NUMERIC,
  "=trig!dk1"                              NUMERIC,
  "=trig_not_dk1"                          NUMERIC,
  "=trig_not_dm1"                          NUMERIC,
  "=trig!dm1"                              NUMERIC,
  "=trig!do1"                              NUMERIC,
  "=trig_not_do1"                          NUMERIC,
  "=trig_not_dq1"                          NUMERIC,
  "=trig!dq1"                              NUMERIC,
  "=trig_not_ds1"                          NUMERIC,
  "=trig!ds1"                              NUMERIC,
  "=trig_not_du1"                          NUMERIC,
  "=trig!du1"                              NUMERIC,
  "=trig_not_dw1"                          NUMERIC,
  "=trig!dw1"                              NUMERIC,
  "=trig_not_dy1"                          NUMERIC,
  "=trig!dy1"                              NUMERIC,
  "=trig!ea1"                              NUMERIC,
  "=trig_not_ea1"                          NUMERIC,
  "=trig_not_ec1"                          NUMERIC,
  "=trig!ec1"                              NUMERIC,
  "=trig_not_ee1"                          NUMERIC,
  "=trig!ee1"                              NUMERIC,
  "=trig!eg1"                              NUMERIC,
  "=trig_not_eg1"                          NUMERIC,
  "=trig!ei1"                              NUMERIC,
  "=trig_not_ei1"                          NUMERIC,
  "=trig_not_ek1"                          NUMERIC,
  "=trig!ek1"                              NUMERIC,
  "=trig_not_em1"                          NUMERIC,
  "=trig!em1"                              NUMERIC,
  "=trig_not_eo1"                          NUMERIC,
  "=trig!eo1"                              NUMERIC,
  source_run_id      BIGINT,
  computed_at        TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (as_of_date, symbol)
);

-- drv_cat_earnings
DROP TABLE IF EXISTS drv_cat_earnings CASCADE;
CREATE TABLE drv_cat_earnings (
  as_of_date         DATE NOT NULL,
  symbol             TEXT NOT NULL,
  price_earnings_ratio_current             NUMERIC,
  "price_/_earnings_ratio_current"         NUMERIC,
  price_book_value_ratio_current           NUMERIC,
  "price_/_book_value_ratio_current"       NUMERIC,
  earningsdays                             NUMERIC,
  source_run_id      BIGINT,
  computed_at        TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (as_of_date, symbol)
);

-- drv_cat_etf
DROP TABLE IF EXISTS drv_cat_etf CASCADE;
CREATE TABLE drv_cat_etf (
  as_of_date         DATE NOT NULL,
  symbol             TEXT NOT NULL,
  etf_bottom                               NUMERIC,
  etf_top                                  NUMERIC,
  etf                                      NUMERIC,
  ii                                       NUMERIC,
  etf_date                                 NUMERIC,
  etf_entry                                NUMERIC,
  etf_cont                                 NUMERIC,
  source_run_id      BIGINT,
  computed_at        TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (as_of_date, symbol)
);

-- drv_cat_fundamentals
DROP TABLE IF EXISTS drv_cat_fundamentals CASCADE;
CREATE TABLE drv_cat_fundamentals (
  as_of_date         DATE NOT NULL,
  symbol             TEXT NOT NULL,
  beta                                     NUMERIC,
  market_cap                               NUMERIC,
  long_term_debt_to_capital_current_ltm    NUMERIC,
  return_on_equity_roe_current_ltm         NUMERIC,
  eps                                      NUMERIC,
  div_yield_current                        NUMERIC,
  "dividend?"                              NUMERIC,
  short_ratio                              NUMERIC,
  float                                    NUMERIC,
  shares_out                               NUMERIC,
  source_run_id      BIGINT,
  computed_at        TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (as_of_date, symbol)
);

-- drv_cat_he_outlook
DROP TABLE IF EXISTS drv_cat_he_outlook CASCADE;
CREATE TABLE drv_cat_he_outlook (
  as_of_date         DATE NOT NULL,
  symbol             TEXT NOT NULL,
  call_entry                               TEXT,
  call_cont                                TEXT,
  he_outlook                               TEXT,
  he_ol_sector                             TEXT,
  he_entry                                 TEXT,
  he_cont                                  TEXT,
  source_run_id      BIGINT,
  computed_at        TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (as_of_date, symbol)
);

-- drv_cat_holdings_dollars
DROP TABLE IF EXISTS drv_cat_holdings_dollars CASCADE;
CREATE TABLE drv_cat_holdings_dollars (
  as_of_date         DATE NOT NULL,
  symbol             TEXT NOT NULL,
  cs_date                                  NUMERIC,
  numactionable                            NUMERIC,
  index                                    NUMERIC,
  stocks                                   NUMERIC,
  rh                                       NUMERIC,
  long                                     NUMERIC,
  short                                    NUMERIC,
  amt_type                                 NUMERIC,
  unit                                     NUMERIC,
  min                                      NUMERIC,
  max                                      NUMERIC,
  numtickers_to_include                    NUMERIC,
  numact                                   NUMERIC,
  numf1_seq                                NUMERIC,
  numfidelity                              NUMERIC,
  numcs                                    NUMERIC,
  sell                                     NUMERIC,
  buy                                      NUMERIC,
  my                                       NUMERIC,
  fidelity                                 NUMERIC,
  cs                                       NUMERIC,
  remaining                                NUMERIC,
  pvv_rule                                 NUMERIC,
  tn_stdv                                  NUMERIC,
  td_stdv                                  NUMERIC,
  portfolio                                NUMERIC,
  amount                                   NUMERIC,
  source_run_id      BIGINT,
  computed_at        TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (as_of_date, symbol)
);

-- drv_cat_identity
DROP TABLE IF EXISTS drv_cat_identity CASCADE;
CREATE TABLE drv_cat_identity (
  as_of_date         DATE NOT NULL,
  symbol             TEXT NOT NULL,
  key                                      TEXT,
  y_symbol                                 TEXT,
  company_name                             TEXT,
  tos_daily_export_date                    TEXT,
  tos_weekly_export_date                   TEXT,
  tos_latest_export_date                   TEXT,
  tos_other_export_date                    TEXT,
  sort_symbol                              TEXT,
  ticker                                   TEXT,
  source_run_id      BIGINT,
  computed_at        TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (as_of_date, symbol)
);

-- drv_cat_ii
DROP TABLE IF EXISTS drv_cat_ii CASCADE;
CREATE TABLE drv_cat_ii (
  as_of_date         DATE NOT NULL,
  symbol             TEXT NOT NULL,
  ii_chg                                   NUMERIC,
  ii_final                                 NUMERIC,
  call                                     NUMERIC,
  call_modifier                            NUMERIC,
  rr                                       NUMERIC,
  sg_rk                                    NUMERIC,
  km                                       NUMERIC,
  sgrk_chg                                 NUMERIC,
  sg_strength                              NUMERIC,
  sgs_chg                                  NUMERIC,
  ii_date                                  NUMERIC,
  call_date                                NUMERIC,
  ii_entry                                 NUMERIC,
  ii_cont                                  NUMERIC,
  source_run_id      BIGINT,
  computed_at        TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (as_of_date, symbol)
);

-- drv_cat_index_volatility
DROP TABLE IF EXISTS drv_cat_index_volatility CASCADE;
CREATE TABLE drv_cat_index_volatility (
  as_of_date         DATE NOT NULL,
  symbol             TEXT NOT NULL,
  sp500_volatility                         NUMERIC,
  nasdaq_volatility                        NUMERIC,
  dow_volatility                           NUMERIC,
  russell_volatility                       NUMERIC,
  fcf                                      NUMERIC,
  source_run_id      BIGINT,
  computed_at        TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (as_of_date, symbol)
);

-- drv_cat_macd
DROP TABLE IF EXISTS drv_cat_macd CASCADE;
CREATE TABLE drv_cat_macd (
  as_of_date         DATE NOT NULL,
  symbol             TEXT NOT NULL,
  a_macd_brr                               NUMERIC,
  macd_brr                                 NUMERIC,
  a_macdh_d_brr                            NUMERIC,
  macdh_brr                                NUMERIC,
  a_macdays_streak                         NUMERIC,
  source_run_id      BIGINT,
  computed_at        TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (as_of_date, symbol)
);

-- drv_cat_moving_avg
DROP TABLE IF EXISTS drv_cat_moving_avg CASCADE;
CREATE TABLE drv_cat_moving_avg (
  as_of_date         DATE NOT NULL,
  symbol             TEXT NOT NULL,
  c_20_dma                                 NUMERIC,
  "20_dma"                                 NUMERIC,
  "50_dma"                                 NUMERIC,
  c_50_dma                                 NUMERIC,
  "200_dma"                                NUMERIC,
  c_200_dma                                NUMERIC,
  tntdmax                                  NUMERIC,
  source_run_id      BIGINT,
  computed_at        TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (as_of_date, symbol)
);

-- drv_cat_perf_extremes
DROP TABLE IF EXISTS drv_cat_perf_extremes CASCADE;
CREATE TABLE drv_cat_perf_extremes (
  as_of_date         DATE NOT NULL,
  symbol             TEXT NOT NULL,
  c_3mn_stk_outlook_sd                     NUMERIC,
  c_3w_stk_outlook_sd                      NUMERIC,
  perf3m                                   NUMERIC,
  perf3m_sd                                NUMERIC,
  a_perf2m                                 NUMERIC,
  perf2m_sd                                NUMERIC,
  perf3w                                   NUMERIC,
  perf3w_sd                                NUMERIC,
  a_perf2wk                                NUMERIC,
  perf2wk_sd                               NUMERIC,
  a_perf3d                                 NUMERIC,
  perf3d_sd                                NUMERIC,
  perf3d_value                             NUMERIC,
  perf1d_sd                                NUMERIC,
  perf                                     NUMERIC,
  "52low"                                  NUMERIC,
  c_52low                                  NUMERIC,
  c_52high                                 NUMERIC,
  "52high"                                 NUMERIC,
  c_52_wk_high_pct                         NUMERIC,
  "52_wk_high_pct"                         NUMERIC,
  source_run_id      BIGINT,
  computed_at        TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (as_of_date, symbol)
);

-- drv_cat_price
DROP TABLE IF EXISTS drv_cat_price CASCADE;
CREATE TABLE drv_cat_price (
  as_of_date         DATE NOT NULL,
  symbol             TEXT NOT NULL,
  close                                    NUMERIC,
  last_net_chng                            NUMERIC,
  last_pctchange                           NUMERIC,
  y_mkt_close_export                       NUMERIC,
  y_latest_exp_date                        NUMERIC,
  use_latest                               NUMERIC,
  standarddeviation                        NUMERIC,
  median_sd                                NUMERIC,
  sdormedian                               NUMERIC,
  sdpct                                    NUMERIC,
  a_3mnlow                                 NUMERIC,
  "3mnlow_sd"                              NUMERIC,
  c_3mnlow_sd                              NUMERIC,
  "3mnlowdays"                             NUMERIC,
  c_3mnlowdays                             NUMERIC,
  a_3mnhigh                                NUMERIC,
  c_3mnhigh_sd                             NUMERIC,
  "3mnhigh_sd"                             NUMERIC,
  c_3mnhighdays                            NUMERIC,
  "3mnhighdays"                            NUMERIC,
  c_3mn_min_brrpct                         NUMERIC,
  "3mn_min_brrpct"                         NUMERIC,
  a_3mnhighlow                             NUMERIC,
  "3mnhighlow"                             NUMERIC,
  c_3mnhighlow                             NUMERIC,
  c_3mnhighlowdays                         NUMERIC,
  "3mnhighlowdays"                         NUMERIC,
  a_3wkhighlow                             NUMERIC,
  "3wkhighlow"                             NUMERIC,
  c_3wkhighlow                             NUMERIC,
  c_3wkhighlowdays                         NUMERIC,
  "3wkhighlowdays"                         NUMERIC,
  d_last                                   NUMERIC,
  d_pctchange                              NUMERIC,
  d_net_chng                               NUMERIC,
  d_open                                   NUMERIC,
  d_high                                   NUMERIC,
  d_low                                    NUMERIC,
  l_last                                   NUMERIC,
  l_net_chng                               NUMERIC,
  l_pctchange                              NUMERIC,
  l_open                                   NUMERIC,
  l_high                                   NUMERIC,
  l_low                                    NUMERIC,
  y_last_price                             NUMERIC,
  y_change                                 NUMERIC,
  y_changepct                              NUMERIC,
  y_open                                   NUMERIC,
  y_high                                   NUMERIC,
  y_low                                    NUMERIC,
  last                                     NUMERIC,
  net_chng                                 NUMERIC,
  pctchange                                NUMERIC,
  prev_close                               NUMERIC,
  open                                     NUMERIC,
  high                                     NUMERIC,
  low                                      NUMERIC,
  chg_sd                                   NUMERIC,
  price_direction                          NUMERIC,
  trnd_trr                                 NUMERIC,
  trd_lrr                                  NUMERIC,
  sd_trr                                   NUMERIC,
  sd_mrr                                   NUMERIC,
  sd_lrr                                   NUMERIC,
  free_cash_flow_per_share_current_ltm     NUMERIC,
  source_run_id      BIGINT,
  computed_at        TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (as_of_date, symbol)
);

-- drv_cat_ps
DROP TABLE IF EXISTS drv_cat_ps CASCADE;
CREATE TABLE drv_cat_ps (
  as_of_date         DATE NOT NULL,
  symbol             TEXT NOT NULL,
  ps_rk                                    NUMERIC,
  ps_outlook                               NUMERIC,
  psrk_chg                                 NUMERIC,
  ps_date                                  NUMERIC,
  ps_entry                                 NUMERIC,
  ps_cont                                  NUMERIC,
  source_run_id      BIGINT,
  computed_at        TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (as_of_date, symbol)
);

-- drv_cat_quad_outlook
DROP TABLE IF EXISTS drv_cat_quad_outlook CASCADE;
CREATE TABLE drv_cat_quad_outlook (
  as_of_date         DATE NOT NULL,
  symbol             TEXT NOT NULL,
  asset_class                              NUMERIC,
  sub_asset_class                          NUMERIC,
  industry                                 NUMERIC,
  growth_sector_based                      NUMERIC,
  growth_econ_based                        NUMERIC,
  growth                                   NUMERIC,
  scale                                    NUMERIC,
  solvency                                 NUMERIC,
  "value?"                                 NUMERIC,
  "quality?"                               NUMERIC,
  momentum_score                           NUMERIC,
  momentum                                 NUMERIC,
  sensitivity                              NUMERIC,
  growth_m_ol                              NUMERIC,
  scale_m_ol                               NUMERIC,
  solvency_m_ol                            NUMERIC,
  "value?_m_ol"                            NUMERIC,
  "quality?_m_ol"                          NUMERIC,
  "dividend?_m_ol"                         NUMERIC,
  momentum_m_ol                            NUMERIC,
  sensitivity_m_ol                         NUMERIC,
  "m+ves_equity_style"                     NUMERIC,
  growth_q_ol                              NUMERIC,
  scale_q_ol                               NUMERIC,
  solvency_q_ol                            NUMERIC,
  "value?_q_ol"                            NUMERIC,
  "quality?_q_ol"                          NUMERIC,
  "dividend?_q_ol"                         NUMERIC,
  momentum_q_ol                            NUMERIC,
  sensitivity_q_ol                         NUMERIC,
  "q+ves_equity_style"                     NUMERIC,
  sig_ol                                   NUMERIC,
  sig_rating                               NUMERIC,
  asset_class_m_ol                         NUMERIC,
  equity_sector_m_ol                       NUMERIC,
  m_ves_equity_style                       NUMERIC,
  asset_class_q_ol                         NUMERIC,
  equity_sector_q_ol                       NUMERIC,
  q_ves_equity_style                       NUMERIC,
  st_signal_desc                           NUMERIC,
  st_signal_action                         NUMERIC,
  source_run_id      BIGINT,
  computed_at        TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (as_of_date, symbol)
);

-- drv_cat_risk_range
DROP TABLE IF EXISTS drv_cat_risk_range CASCADE;
CREATE TABLE drv_cat_risk_range (
  as_of_date         DATE NOT NULL,
  symbol             TEXT NOT NULL,
  rr_lrr                                   NUMERIC,
  rr_trr                                   NUMERIC,
  rr_brrpct                                NUMERIC,
  rr_bottom                                NUMERIC,
  rr_top                                   NUMERIC,
  bbrngstrkrule                            NUMERIC,
  bbrngstrkrule_action                     NUMERIC,
  bullriskrng_action                       NUMERIC,
  "!bullriskrng_action"                    NUMERIC,
  not_bullriskrng_action                   NUMERIC,
  riskrng_longs_action                     NUMERIC,
  rr_date                                  NUMERIC,
  rr_entry                                 NUMERIC,
  rr_cont                                  NUMERIC,
  brrpct                                   NUMERIC,
  brrpct_sector                            NUMERIC,
  bbrngstrkrule_desc                       NUMERIC,
  rrbullbear                               NUMERIC,
  rrdesc                                   NUMERIC,
  source_run_id      BIGINT,
  computed_at        TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (as_of_date, symbol)
);

-- drv_cat_rsi
DROP TABLE IF EXISTS drv_cat_rsi CASCADE;
CREATE TABLE drv_cat_rsi (
  as_of_date         DATE NOT NULL,
  symbol             TEXT NOT NULL,
  d_rsi                                    NUMERIC,
  d_iv                                     NUMERIC,
  d_hv                                     NUMERIC,
  l_rsi                                    NUMERIC,
  l_impvolatility                          NUMERIC,
  rsi                                      NUMERIC,
  impvolatility                            NUMERIC,
  source_run_id      BIGINT,
  computed_at        TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (as_of_date, symbol)
);

-- drv_cat_sector_rollup
DROP TABLE IF EXISTS drv_cat_sector_rollup CASCADE;
CREATE TABLE drv_cat_sector_rollup (
  as_of_date         DATE NOT NULL,
  symbol             TEXT NOT NULL,
  "sctr!sector"                            NUMERIC,
  sctr_not_sector                          NUMERIC,
  sector                                   NUMERIC,
  sector_ticker                            NUMERIC,
  source_run_id      BIGINT,
  computed_at        TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (as_of_date, symbol)
);

-- drv_cat_signal_strength
DROP TABLE IF EXISTS drv_cat_signal_strength CASCADE;
CREATE TABLE drv_cat_signal_strength (
  as_of_date         DATE NOT NULL,
  symbol             TEXT NOT NULL,
  ssh_date                                 NUMERIC,
  fh_date                                  NUMERIC,
  sss_entry                                NUMERIC,
  sss_date                                 NUMERIC,
  ss_entry_only                            NUMERIC,
  sss_cont                                 NUMERIC,
  ss_entry                                 NUMERIC,
  ss_cont                                  NUMERIC,
  source_run_id      BIGINT,
  computed_at        TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (as_of_date, symbol)
);

-- drv_cat_trend_trade
DROP TABLE IF EXISTS drv_cat_trend_trade CASCADE;
CREATE TABLE drv_cat_trend_trade (
  as_of_date         DATE NOT NULL,
  symbol             TEXT NOT NULL,
  a_trendvalue                             NUMERIC,
  a_tradevalue                             NUMERIC,
  trend_sd                                 NUMERIC,
  trade_sd                                 NUMERIC,
  trade_trend_sd                           NUMERIC,
  trend_context                            NUMERIC,
  long_trend_total                         NUMERIC,
  long_trend_score                         NUMERIC,
  long_trend_descr                         NUMERIC,
  st_signal_scenario                       NUMERIC,
  st_signal_score                          NUMERIC,
  final_signal_scenario                    NUMERIC,
  final_signal                             NUMERIC,
  tn_td_rule_action                        NUMERIC,
  tn_td_stdv_diff                          NUMERIC,
  tr_td_outlook                            NUMERIC,
  tn_td_rule                               NUMERIC,
  tn_td_rule_desc                          NUMERIC,
  source_run_id      BIGINT,
  computed_at        TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (as_of_date, symbol)
);

-- drv_cat_trig_summary
DROP TABLE IF EXISTS drv_cat_trig_summary CASCADE;
CREATE TABLE drv_cat_trig_summary (
  as_of_date         DATE NOT NULL,
  symbol             TEXT NOT NULL,
  trig_matched_rule1                       TEXT,
  trig_m_rule2                             TEXT,
  trig_m_rule3                             TEXT,
  trig_m_rule4                             TEXT,
  trig_m_rule5                             TEXT,
  trig_m_rule6                             TEXT,
  trig_m_rule7                             TEXT,
  trig_m_rule8                             TEXT,
  trig_m_rule9                             TEXT,
  trig_m_rule10                            TEXT,
  trig_m_rule11                            TEXT,
  trig_rule                                TEXT,
  blanks                                   TEXT,
  negatives                                TEXT,
  positives                                TEXT,
  neg_rank                                 TEXT,
  pos_rank                                 TEXT,
  trig                                     TEXT,
  matched_rule1                            TEXT,
  m_rule2                                  TEXT,
  m_rule3                                  TEXT,
  m_rule4                                  TEXT,
  m_rule5                                  TEXT,
  m_rule6                                  TEXT,
  m_rule7                                  TEXT,
  m_rule8                                  TEXT,
  m_rule9                                  TEXT,
  m_rule10                                 TEXT,
  m_rule11                                 TEXT,
  source_run_id      BIGINT,
  computed_at        TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (as_of_date, symbol)
);

-- drv_cat_volatility_regime
DROP TABLE IF EXISTS drv_cat_volatility_regime CASCADE;
CREATE TABLE drv_cat_volatility_regime (
  as_of_date         DATE NOT NULL,
  symbol             TEXT NOT NULL,
  d_vlt_rulecode                           NUMERIC,
  d_vlt_ruleaction                         NUMERIC,
  price_zone                               NUMERIC,
  d_vlt_caution                            NUMERIC,
  d_vlt_ruledesc                           NUMERIC,
  volatility_regime                        NUMERIC,
  source_run_id      BIGINT,
  computed_at        TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (as_of_date, symbol)
);

-- drv_cat_volume
DROP TABLE IF EXISTS drv_cat_volume CASCADE;
CREATE TABLE drv_cat_volume (
  as_of_date         DATE NOT NULL,
  symbol             TEXT NOT NULL,
  a_volumespike                            NUMERIC,
  volumespike                              NUMERIC,
  vs_spike                                 NUMERIC,
  vs_price_change                          NUMERIC,
  vs_price_change_sd                       NUMERIC,
  l_vlm                                    NUMERIC,
  w_vlm                                    NUMERIC,
  volume                                   NUMERIC,
  volumerateofchange                       NUMERIC,
  w_avg_vlm_10day                          NUMERIC,
  vlm_10_factor                            NUMERIC,
  vlm_10_day_pct                           NUMERIC,
  w_avg_vlm_3m                             NUMERIC,
  vlm_3_m_factor                           NUMERIC,
  vlm_3m_pct                               NUMERIC,
  vlm_score                                NUMERIC,
  w_vlm_rulecode                           NUMERIC,
  vlm_action                               NUMERIC,
  vlm_ruledesc                             NUMERIC,
  vlm_ruleaction                           NUMERIC,
  vlm_desc                                 NUMERIC,
  source_run_id      BIGINT,
  computed_at        TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (as_of_date, symbol)
);

